/**
 * TRACK LISTINGS — each record's running order, exactly as its source lists it.
 *
 * The one place a track's title and length are written. The record files
 * (content/records.ts) read their tracklists from here, with the edition and
 * the source they belong to; the archive's sleeves (content/sleeves.ts) read
 * the lengths. Kept apart from the files so that what draws a sleeve does not
 * carry the files' text with it.
 *
 * Rows are [title, length, note?], keyed by catalogue number. A `null` title
 * is a track the source lists without one.
 */
export type TrackRow = readonly [title: string | null, length: string] | readonly [title: string | null, length: string, note: string];

export const tracklists = {
  "SC—AH—01": [
    ["Mysterons", "5:02"],
    ["Sour Times", "4:14"],
    ["Strangers", "3:55"],
    ["It Could Be Sweet", "4:16"],
    ["Wandering Star", "4:51"],
    ["It's a Fire", "3:48", "Not on vinyl LP or original UK and Europe versions"],
    ["Numb", "3:54"],
    ["Roads", "5:02"],
    ["Pedestal", "3:39"],
    ["Biscuit", "5:01"],
    ["Glory Box", "5:06"],
  ],
  "SC—AH—02": [
    ["Low Place Like Home", "4:37"],
    ["Tesko Suicide", "3:44"],
    ["6 Underground", "4:05"],
    ["Becoming X", "4:14"],
    ["Spin Spin Sugar", "4:20"],
    ["Post-Modern Sleaze", "5:11"],
    ["Waterbaby", "4:10"],
    ["Roll On", "4:27"],
    ["Wasted Early Sunday Morning", "4:27"],
    ["Walking Zero", "4:31"],
    ["How Do", "5:01"],
  ],
  "SC—AH—03": [
    ["Angel", "6:18"],
    ["Risingson", "4:58"],
    ["Teardrop", "5:29"],
    ["Inertia Creeps", "5:56"],
    ["Exchange", "4:11"],
    ["Dissolved Girl", "6:07"],
    ["Man Next Door", "5:55"],
    ["Black Milk", "6:20"],
    ["Mezzanine", "5:54"],
    ["Group Four", "8:13"],
    ["(Exchange)", "4:08"],
  ],
  "SC—SF—04": [
    ["La Femme d'argent", "7:08"],
    ["Sexy Boy", "4:57"],
    ["All I Need", "4:28"],
    ["Kelly Watch the Stars", "3:44"],
    ["Talisman", "4:16"],
    ["Remember", "2:34"],
    ["You Make It Easy", "4:00"],
    ["Ce matin là", "3:38"],
    ["New Star in the Sky (Chanson pour Solal)", "5:38"],
    ["Le Voyage de Pénélope", "3:10"],
  ],
  "SC—SF—05": [
    ["Honey", "3:28"],
    ["Find My Baby", "4:00"],
    ["Porcelain", "4:01"],
    ["Why Does My Heart Feel So Bad?", "4:24"],
    ["South Side", "3:50"],
    ["Rushing", "3:01"],
    ["Bodyrock", "3:36"],
    ["Natural Blues", "4:14"],
    ["Machete", "3:38"],
    ["7", "1:02"],
    ["Run On", "3:45"],
    ["Down Slow", "1:35"],
    ["If Things Were Perfect", "4:18"],
    ["Everloving", "3:26"],
    ["Inside", "4:49"],
    ["Guitar Flute & String", "2:09"],
    ["The Sky Is Broken", "4:20"],
    ["My Weakness", "3:42"],
  ],
  "SC—SF—06": [
    ["I Have Seen", "5:07"],
    ["Polaris", "4:48"],
    ["Destiny", "5:38"],
    ["Give It Away", "5:17"],
    ["Simple Things", "4:24"],
    ["Red Dust", "5:40"],
    ["Distractions", "5:16"],
    ["In the Waiting Line", "4:35"],
    ["Out of Town", "4:48"],
    ["This World", "5:37"],
    ["Likufanele", "6:24"],
    ["End Theme", "3:38"],
  ],
  "SC—CF—07": [
    ["Best Foot Forward", "0:49"],
    ["Building Steam with a Grain of Salt", "6:40"],
    ["The Number Song", "4:40"],
    ["Changeling / Transmission 1", "7:51"],
    ["What Does Your Soul Look Like (Part 4)", "5:08"],
    [null, "0:24"],
    ["Stem/Long Stem / Transmission 2", "9:21"],
    ["Mutual Slump", "4:02"],
    ["Organ Donor", "1:57"],
    ["Why Hip Hop Sucks in '96", "0:43"],
    ["Midnight in a Perfect World", "4:57"],
    ["Napalm Brain/Scatter Brain", "9:23"],
    ["What Does Your Soul Look Like (Part 1 – Blue Sky Revisit) / Transmission 3", "7:28"],
  ],
  "SC—CF—08": [
    ["Block Rockin' Beats", "5:14"],
    ["Dig Your Own Hole", "5:27"],
    ["Elektrobank", "8:18"],
    ["Piku", "4:54"],
    ["Setting Sun", "5:29"],
    ["It Doesn't Matter", "6:14"],
    ["Don't Stop the Rock", "4:50"],
    ["Get Up on It Like This", "2:47"],
    ["Lost in the K-Hole", "3:52"],
    ["Where Do I Begin", "6:56"],
    ["The Private Psychedelic Reel", "9:22"],
  ],
  "SC—CF—09": [
    ["Right Here, Right Now", "6:27"],
    ["The Rockafeller Skank", "6:53"],
    ["Fucking in Heaven", "3:55", "Retitled on the North American version"],
    ["Gangster Tripping", "5:20"],
    ["Build It Up – Tear It Down", "5:05"],
    ["Kalifornia", "5:53"],
    ["Soul Surfing", "4:56"],
    ["You're Not from Brighton", "5:20"],
    ["Praise You", "5:23"],
    ["Love Island", "5:18"],
    ["Acid 8000", "7:28"],
  ],
  "SC—AS—10": [
    ["Airbag", "4:44"],
    ["Paranoid Android", "6:23"],
    ["Subterranean Homesick Alien", "4:27"],
    ["Exit Music (For a Film)", "4:24"],
    ["Let Down", "4:59"],
    ["Karma Police", "4:21"],
    ["Fitter Happier", "1:57"],
    ["Electioneering", "3:50"],
    ["Climbing Up the Walls", "4:45"],
    ["No Surprises", "3:48"],
    ["Lucky", "4:19"],
    ["The Tourist", "5:24"],
  ],
  "SC—AS—11": [
    ["Brakhage", "5:30"],
    ["Miss Modular", "4:29"],
    ["The Flower Called Nowhere", "4:55"],
    ["Diagonals", "5:15"],
    ["Prisoner of Mars", "4:03"],
    ["Rainbo Conversation", "4:46"],
    ["Refractions in the Plastic Pulse", "17:32"],
    ["Parsec", "5:34"],
    ["Ticker-Tape of the Unconscious", "4:45"],
    ["Contronatura", "9:03"],
  ],
  "SC—AS—12": [
    ["Guns Blazing (Drums of Death Part 1)", "5:01"],
    ["Unkle Main Title Theme", "3:24"],
    ["Bloodstain", "5:57"],
    ["Unreal", "5:10"],
    ["Lonely Soul", "8:56"],
    ["Getting Ahead in the Lucrative Field of Artist Management", "0:56"],
    ["Nursery Rhyme / Breather", "4:45"],
    ["Celestial Annihilation", "4:44"],
    ["The Knock (Drums of Death Part 2)", "3:58"],
    ["Chaos", "4:42"],
    ["Rabbit in Your Headlights", "6:20"],
    ["Outro (Mandatory)", "1:06"],
  ],
} as const satisfies Readonly<Record<string, readonly TrackRow[]>>;

export type TracklistKey = keyof typeof tracklists;
